ALTER TABLE MEMBER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_MEMBER;

/* 유저 */
DROP TABLE MEMBER
	CASCADE CONSTRAINTS;

/* 유저 */
CREATE TABLE MEMBER (
	IDX NUMBER(8) NOT NULL, /* 회원번호 */
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	PWD VARCHAR2(30) NOT NULL, /* 비밀번호 */
	EMAIL VARCHAR2(30) NOT NULL, /* 이메일 */
	NAME VARCHAR2(25) NOT NULL, /* 이름 */
	TEL VARCHAR2(11) NOT NULL, /* 연락처 */
	STAT NUMBER(1) NOT NULL, /* 회원상태 */
	INDATE DATE, /* 가입일 */
	POINT NUMBER(8) NOT NULL /* 포인트 */
);

COMMENT ON TABLE MEMBER IS '유저';

COMMENT ON COLUMN MEMBER.IDX IS '회원번호';

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.NAME IS '이름';

COMMENT ON COLUMN MEMBER.TEL IS '연락처';

COMMENT ON COLUMN MEMBER.STAT IS '회원상태';

COMMENT ON COLUMN MEMBER.INDATE IS '가입일';

COMMENT ON COLUMN MEMBER.POINT IS '포인트';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		IDX ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			IDX
		);

DROP SEQUENCE MEMBER_SEQ;

CREATE  SEQUENCE MEMBER_SEQ NOCACHE; -- 시퀸스