ALTER TABLE TRAVEL_SAVE
	DROP
		CONSTRAINT FK_MEMBER_TO_TRAVEL_SAVE
		CASCADE;

ALTER TABLE TRAVEL_SAVE
	DROP
		CONSTRAINT FK_TRAVEL_TO_TRAVEL_SAVE
		CASCADE;

ALTER TABLE TRAVEL_SAVE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_TRAVEL_SAVE;

/* 여행지찜 */
DROP TABLE TRAVEL_SAVE
	CASCADE CONSTRAINTS;

/* 여행지찜 */
CREATE TABLE TRAVEL_SAVE (
	IDX NUMBER(8) NOT NULL, /* 회원번호 */
	TNUM NUMBER(8) NOT NULL, /* 여행지번호 */
	SDATE DATE /* 찜한날짜 */
);

COMMENT ON TABLE TRAVEL_SAVE IS '여행지찜';

COMMENT ON COLUMN TRAVEL_SAVE.IDX IS '회원번호';

COMMENT ON COLUMN TRAVEL_SAVE.TNUM IS '여행지번호';

COMMENT ON COLUMN TRAVEL_SAVE.SDATE IS '찜한날짜';

CREATE UNIQUE INDEX PK_TRAVEL_SAVE
	ON TRAVEL_SAVE (
		IDX ASC,
		TNUM ASC
	);

ALTER TABLE TRAVEL_SAVE
	ADD
		CONSTRAINT PK_TRAVEL_SAVE
		PRIMARY KEY (
			IDX,
			TNUM
		);

ALTER TABLE TRAVEL_SAVE
	ADD
		CONSTRAINT FK_MEMBER_TO_TRAVEL_SAVE
		FOREIGN KEY (
			IDX
		)
		REFERENCES MEMBER (
			IDX
		);

ALTER TABLE TRAVEL_SAVE
	ADD
		CONSTRAINT FK_TRAVEL_TO_TRAVEL_SAVE
		FOREIGN KEY (
			TNUM
		)
		REFERENCES TRAVEL (
			TNUM
		);