ALTER TABLE PRODUCT_CATEGORY
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PRODUCT_CATEGORY;

/* 카테고리 */
DROP TABLE PRODUCT_CATEGORY
	CASCADE CONSTRAINTS;

/* 카테고리 */
CREATE TABLE PRODUCT_CATEGORY (
	CG_NUM NUMBER(3) NOT NULL, /* 카테고리번호 */
	CG_NAME VARCHAR2(20) /* 카테고리이름 */
);

COMMENT ON TABLE PRODUCT_CATEGORY IS '카테고리';

COMMENT ON COLUMN PRODUCT_CATEGORY.CG_NUM IS '카테고리번호';

COMMENT ON COLUMN PRODUCT_CATEGORY.CG_NAME IS '카테고리이름';

CREATE UNIQUE INDEX PK_PRODUCT_CATEGORY
	ON PRODUCT_CATEGORY (
		CG_NUM ASC
	);

ALTER TABLE PRODUCT_CATEGORY
	ADD
		CONSTRAINT PK_PRODUCT_CATEGORY
		PRIMARY KEY (
			CG_NUM
		);