ALTER TABLE ORDERDESC
	DROP
		CONSTRAINT FK_MEMBER_TO_ORDERDESC
		CASCADE;

ALTER TABLE ORDERDESC
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_ORDERDESC;

/* 주문개요 */
DROP TABLE ORDERDESC
	CASCADE CONSTRAINTS;

/* 주문개요 */
CREATE TABLE ORDERDESC (
	ONUM VARCHAR2(30) NOT NULL, /* 주문번호 */
	OTOTALPOINT NUMBER(10) NOT NULL, /* 결제총포인트 */
	OPAYSTATE VARCHAR2(20) NOT NULL, /* 결제상태 */
	ORDERDATE DATE NOT NULL, /* 주문일자 */
	IDX_FK NUMBER(8) NOT NULL /* 회원번호 */
);

COMMENT ON TABLE ORDERDESC IS '주문개요';

COMMENT ON COLUMN ORDERDESC.ONUM IS '주문번호';

COMMENT ON COLUMN ORDERDESC.OTOTALPOINT IS '결제총포인트';

COMMENT ON COLUMN ORDERDESC.OPAYSTATE IS '결제상태';

COMMENT ON COLUMN ORDERDESC.ORDERDATE IS '주문일자';

COMMENT ON COLUMN ORDERDESC.IDX_FK IS '회원번호';

CREATE UNIQUE INDEX PK_ORDERDESC
	ON ORDERDESC (
		ONUM ASC
	);

ALTER TABLE ORDERDESC
	ADD
		CONSTRAINT PK_ORDERDESC
		PRIMARY KEY (
			ONUM
		);

ALTER TABLE ORDERDESC
	ADD
		CONSTRAINT FK_MEMBER_TO_ORDERDESC
		FOREIGN KEY (
			IDX_FK
		)
		REFERENCES MEMBER (
			IDX
		);