ALTER TABLE ORDER_PRODUCT
	DROP
		CONSTRAINT FK_PRODUCT_TO_ORDER_PRODUCT
		CASCADE;

ALTER TABLE ORDER_PRODUCT
	DROP
		CONSTRAINT FK_ORDERDESC_TO_ORDER_PRODUCT
		CASCADE;

ALTER TABLE ORDER_PRODUCT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_ORDER_PRODUCT;

/* 주문상품 */
DROP TABLE ORDER_PRODUCT
	CASCADE CONSTRAINTS;

/* 주문상품 */
CREATE TABLE ORDER_PRODUCT (
	ONUM VARCHAR2(30) NOT NULL, /* 주문번호 */
	PNUM_FK NUMBER(8) NOT NULL, /* 상품번호 */
	OPOINT NUMBER(10) NOT NULL, /* 포인트 */
	OQTY NUMBER(8) NOT NULL, /* 수량 */
	PIMAGE VARCHAR2(200) /* 상품대표이미지 */
);

COMMENT ON TABLE ORDER_PRODUCT IS '주문상품';

COMMENT ON COLUMN ORDER_PRODUCT.ONUM IS '주문번호';

COMMENT ON COLUMN ORDER_PRODUCT.PNUM_FK IS '상품번호';

COMMENT ON COLUMN ORDER_PRODUCT.OPOINT IS '포인트';

COMMENT ON COLUMN ORDER_PRODUCT.OQTY IS '수량';

COMMENT ON COLUMN ORDER_PRODUCT.PIMAGE IS '상품대표이미지';

CREATE UNIQUE INDEX PK_ORDER_PRODUCT
	ON ORDER_PRODUCT (
		ONUM ASC,
		PNUM_FK ASC
	);

ALTER TABLE ORDER_PRODUCT
	ADD
		CONSTRAINT PK_ORDER_PRODUCT
		PRIMARY KEY (
			ONUM,
			PNUM_FK
		);

ALTER TABLE ORDER_PRODUCT
	ADD
		CONSTRAINT FK_PRODUCT_TO_ORDER_PRODUCT
		FOREIGN KEY (
			PNUM_FK
		)
		REFERENCES PRODUCT (
			PNUM
		);

ALTER TABLE ORDER_PRODUCT
	ADD
		CONSTRAINT FK_ORDERDESC_TO_ORDER_PRODUCT
		FOREIGN KEY (
			ONUM
		)
		REFERENCES ORDERDESC (
			ONUM
		);