ALTER TABLE TRAVEL
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_TRAVEL;

/* 여행 */
DROP TABLE TRAVEL
	CASCADE CONSTRAINTS;

/* 여행 */
CREATE TABLE TRAVEL (
	TNUM NUMBER(8) NOT NULL, /* 여행지번호 */
	TTITLE VARCHAR2(20) NOT NULL, /* 제목 */
	TNAME VARCHAR2(200) NOT NULL, /* 여행지 */
	TADDR VARCHAR2(200) NOT NULL, /* 주소 */
	TTHEME VARCHAR2(20) NOT NULL, /* 여행테마 */
	TCONTENT VARCHAR2(300) NOT NULL, /* 내용 */
	TFILE1 VARCHAR2(200), /* 첨부파일1 */
	TFILE2 VARCHAR2(200), /* 첨부파일2 */
	TFILE3 VARCHAR2(200), /* 첨부파일3 */
	TDATE DATE /* 등록일 */
);

COMMENT ON TABLE TRAVEL IS '여행';

COMMENT ON COLUMN TRAVEL.TNUM IS '여행지번호';

COMMENT ON COLUMN TRAVEL.TTITLE IS '제목';

COMMENT ON COLUMN TRAVEL.TNAME IS '여행지';

COMMENT ON COLUMN TRAVEL.TADDR IS '주소';

COMMENT ON COLUMN TRAVEL.TTHEME IS '여행테마';

COMMENT ON COLUMN TRAVEL.TCONTENT IS '내용';

COMMENT ON COLUMN TRAVEL.TFILE1 IS '첨부파일1';

COMMENT ON COLUMN TRAVEL.TFILE2 IS '첨부파일2';

COMMENT ON COLUMN TRAVEL.TFILE3 IS '첨부파일3';

COMMENT ON COLUMN TRAVEL.TDATE IS '등록일';

CREATE UNIQUE INDEX PK_TRAVEL
	ON TRAVEL (
		TNUM ASC
	);

ALTER TABLE TRAVEL
	ADD
		CONSTRAINT PK_TRAVEL
		PRIMARY KEY (
			TNUM
		);