ALTER TABLE MEMBER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_MEMBER;

/* 유저 */
DROP TABLE MEMBER
	CASCADE CONSTRAINTS;

DROP SEQUENCE MEMBER_SEQ;

/* 유저 */
CREATE TABLE MEMBER (
	IDX NUMBER(10) NOT NULL, /* 회원번호 PK */
	ID VARCHAR2(20) NOT NULL, /* 아이디 UNIQUE */
	PWD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	EMAIL VARCHAR2(50) NOT NULL, /* 이메일 UNIQUE */
	NICK VARCHAR2(50) NOT NULL, /* 닉네임 UNIQUE */
	TEL VARCHAR2(11) NOT NULL, /* 연락처 UNIQUE */
	IMAGE VARCHAR2(500), /* 프로필 사진 */
	STAT NUMBER(1) NOT NULL, /* 회원상태 */
	INDATE DATE, /* 가입일 */
	POINT NUMBER(10) NOT NULL /* 포인트 */
);

COMMENT ON TABLE MEMBER IS '유저';

COMMENT ON COLUMN MEMBER.IDX IS '회원번호';

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.NICK IS '닉네임';

COMMENT ON COLUMN MEMBER.TEL IS '연락처';

COMMENT ON COLUMN MEMBER.IMAGE IS '프로필사진';

COMMENT ON COLUMN MEMBER.STAT IS '회원상태';

COMMENT ON COLUMN MEMBER.INDATE IS '가입일';

COMMENT ON COLUMN MEMBER.POINT IS '포인트';

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		IDX ASC
	);

CREATE UNIQUE INDEX PK_MEMBER_ID
	ON MEMBER (
		ID ASC
	);

CREATE UNIQUE INDEX PK_MEMBER_EMAIL
	ON MEMBER (
		EMAIL ASC
	);


CREATE UNIQUE INDEX PK_MEMBER_NICK
	ON MEMBER (
		NICK ASC
	);

CREATE UNIQUE INDEX PK_MEMBER_TEL
	ON MEMBER (
		TEL ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			IDX
		);

CREATE SEQUENCE MEMBER_SEQ NOCACHE; -- 시퀸스