ALTER TABLE POINT
	DROP
		CONSTRAINT FK_MEMBER_TO_POINT
		CASCADE;

ALTER TABLE POINT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_POINT;

/* 포인트(어드민) */
DROP TABLE POINT
	CASCADE CONSTRAINTS;

/* 포인트(어드민) */
CREATE TABLE POINT (
	PIDX VARCHAR2(8) NOT NULL, /* 구분번호 PK */
	PCONTENT VARCHAR2(300), /* 적립내용 */
	PDATE DATE, /* 적립일 */
	PSAVEPOINT NUMBER(8), /* 적립포인트 */
	PTOTALPOINT NUMBER(8) NOT NULL, /* 총포인트 */
	IDX NUMBER(8) NOT NULL /* 회원번호 FK */
);

COMMENT ON TABLE POINT IS '포인트(어드민)';

COMMENT ON COLUMN POINT.PIDX IS '구분번호';

COMMENT ON COLUMN POINT.PCONTENT IS '적립내용';

COMMENT ON COLUMN POINT.PDATE IS '적립일';

COMMENT ON COLUMN POINT.PSAVEPOINT IS '적립포인트';

COMMENT ON COLUMN POINT.PTOTALPOINT IS '총포인트';

COMMENT ON COLUMN POINT.IDX IS '회원번호';

CREATE UNIQUE INDEX PK_POINT
	ON POINT (
		PIDX ASC
	);

ALTER TABLE POINT
	ADD
		CONSTRAINT PK_POINT
		PRIMARY KEY (
			PIDX
		);

ALTER TABLE POINT
	ADD
		CONSTRAINT FK_MEMBER_TO_POINT
		FOREIGN KEY (
			IDX
		)
		REFERENCES MEMBER (
			IDX
		);